/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MummyWestAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MummyWestAddonDeed();
			}
		}

		[ Constructable ]
		public MummyWestAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 7565 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 7564 );
			AddComponent( ac, 0, 0, 0 );

		}

		public MummyWestAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MummyWestAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MummyWestAddon();
			}
		}

		[Constructable]
		public MummyWestAddonDeed()
		{
			Name = "MummyWest";
		}

		public MummyWestAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}