/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MummySouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MummySouthAddonDeed();
			}
		}

		[ Constructable ]
		public MummySouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 7563 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 7562 );
			AddComponent( ac, 0, 0, 0 );

		}

		public MummySouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MummySouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MummySouthAddon();
			}
		}

		[Constructable]
		public MummySouthAddonDeed()
		{
			Name = "MummySouth";
		}

		public MummySouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}