/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GraveYardSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GraveYardSouthAddonDeed();
			}
		}

		[ Constructable ]
		public GraveYardSouthAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 3809 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 3809 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 3809 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 3809 );
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 3807 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 3807 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 3807 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 3807 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 4454 );
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 4456 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 4462 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 4466 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 6013 );
			AddComponent( ac, 3, 2, 0 );
            ac.Name = "Grave Yard";
            
            AddComponent(ac, 0, 0, 0);

		}

		public GraveYardSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GraveYardSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GraveYardSouthAddon();
			}
		}

		[Constructable]
		public GraveYardSouthAddonDeed()
		{
			Name = "Grave Yard South";
            
		}

		public GraveYardSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}