/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SkullSpikeAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SkullSpikeAddonDeed();
			}
		}

		[ Constructable ]
		public SkullSpikeAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 8700 );
			AddComponent( ac, 0, 0, 0 );

		}

		public SkullSpikeAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SkullSpikeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SkullSpikeAddon();
			}
		}

		[Constructable]
		public SkullSpikeAddonDeed()
		{
			Name = "SkullSpike";
           
		}

		public SkullSpikeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}