<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Launcher</AssemblyName>
    <ApplicationIcon>servuo.ico</ApplicationIcon>
    <StartupObject>Launcher.Launcher</StartupObject>
    <ApplicationManifest>Launcher.exe.manifest</ApplicationManifest>
    <AppendTargetFrameworkToOutputPath>False</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseVSHostingProcess>False</UseVSHostingProcess>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\</OutputPath>
    <DefineConstants>TRACE;DEBUG;NEWTIMERS;ServUO</DefineConstants>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\</OutputPath>
    <DefineConstants>TRACE;NEWTIMERS;ServUO</DefineConstants>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ultima\Ultima.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="servuo.ico" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy $(TargetPath) $(ProjectDir)\..\Launcher.exe &amp;&amp; copy $(TargetDir)\Ultima.dll $(ProjectDir)\..\Ultima.dll" />
  </Target>
</Project>