/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AWitchAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AWitchAddonDeed();
			}
		}

		[ Constructable ]
		public AWitchAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 10092 );
            ac.Name = "A Witch †Halloween 2007†";
            
			AddComponent( ac, 0, 0, 0 );

		}

		public AWitchAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AWitchAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AWitchAddon();
			}
		}

		[Constructable]
		public AWitchAddonDeed()
		{
			Name = "A Witch";
		}

		public AWitchAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}