/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GingerbreadHouseAddon : BaseAddon
	{
		

            public override BaseAddonDeed Deed
		{
			get
			{
				return new GingerbreadHouseAddonDeed();
			}
		}

		[ Constructable ]
		public GingerbreadHouseAddon()
		{
		      Name = "Gingerbread House";

                  AddComponent( new AddonComponent( 11237 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 11238 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 11239 ), 1, 0, 0 );
			

		}

		public GingerbreadHouseAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GingerbreadHouseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GingerbreadHouseAddon();
			}
		}

		[Constructable]
		public GingerbreadHouseAddonDeed()
		{
			Name = "A Gingerbread House Deed";
		      LootType = LootType.Blessed;

            }

		public GingerbreadHouseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}