// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class BonfireAddon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new BonfireAddonDeed();}}
		[ Constructable ]
		public BonfireAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 6019 );
			AddComponent( ac, -4, 2, 0 );

			ac = new AddonComponent( 6019 );
			AddComponent( ac, -4, 1, 0 );

			ac = new AddonComponent( 6019 );
			AddComponent( ac, -4, 0, 0 );

			ac = new AddonComponent( 6019 );
			AddComponent( ac, -4, -1, 0 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, 2, 3, 0 );

			ac = new AddonComponent( 3388 );
			AddComponent( ac, 2, 3, 0 );

			ac = new AddonComponent( 3388 );
			AddComponent( ac, 0, 3, 0 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, 0, 3, 0 );

			ac = new AddonComponent( 4968 );
			AddComponent( ac, 2, 4, 0 );

			ac = new AddonComponent( 4967 );
			AddComponent( ac, 1, 3, 0 );

			ac = new AddonComponent( 12794 );
			AddComponent( ac, 1, 3, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 2, 3, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 1, 0, 12 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -1, 3, 12 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 1, 2, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, 1, 0, 12 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 1, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 0, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 1, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 0, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 2, 0 );

			ac = new AddonComponent( 14742 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 2, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 1, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, -1, 0 );

			ac = new AddonComponent( 3555 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -2, 2, 1 );

			ac = new AddonComponent( 3555 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, -1, 2 );

			ac = new AddonComponent( 3555 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, -1, 0 );

			ac = new AddonComponent( 3555 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 1, 12 );

			ac = new AddonComponent( 3555 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -2, 2, 0 );

			ac = new AddonComponent( 3555 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 3555 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 0, 2 );

			ac = new AddonComponent( 14734 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 2, 12 );

			ac = new AddonComponent( 6006 );
			AddComponent( ac, 4, 3, 0 );

			ac = new AddonComponent( 4970 );
			AddComponent( ac, -3, 3, 0 );

			ac = new AddonComponent( 4970 );
			AddComponent( ac, 4, 0, 0 );

			ac = new AddonComponent( 4963 );
			AddComponent( ac, -3, 1, 0 );

			ac = new AddonComponent( 4963 );
			AddComponent( ac, -1, -3, 0 );

			ac = new AddonComponent( 4963 );
			AddComponent( ac, 4, -1, 0 );

			ac = new AddonComponent( 14732 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 2, 12 );

			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 2, 12 );

			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 1, 0, 24 );

			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 2, 1, 14 );

			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 2, 12 );

			ac = new AddonComponent( 6571 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 2, 12 );

			ac = new AddonComponent( 14741 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 3388 );
			ac.Hue = 1161;
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 3387 );
			ac.Hue = 1161;
			AddComponent( ac, 2, 1, 12 );

			ac = new AddonComponent( 3387 );
			ac.Hue = 1161;
			AddComponent( ac, 2, 2, 12 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 3, 1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 0, 1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 0, 0, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 0, -1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 0, -2, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -1, 1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -1, 0, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -1, -1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -1, -2, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -2, 1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -2, 0, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -2, -1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -2, -2, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, -2, -2, 3 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 1, 2, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 2, 0, 14 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 0, 1, 12 );

			ac = new AddonComponent( 4435 );
			ac.Hue = 1161;
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 4967 );
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 4964 );
			AddComponent( ac, -2, -1, 0 );

			ac = new AddonComponent( 4964 );
			AddComponent( ac, 2, -3, 0 );

			ac = new AddonComponent( 4964 );
			AddComponent( ac, -1, 4, 0 );

			ac = new AddonComponent( 4963 );
			AddComponent( ac, -2, -2, 0 );

			ac = new AddonComponent( 4963 );
			AddComponent( ac, 0, -2, 0 );

			ac = new AddonComponent( 4963 );
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 4963 );
			AddComponent( ac, 0, 4, 0 );

			ac = new AddonComponent( 6010 );
			AddComponent( ac, -2, 4, 0 );

			ac = new AddonComponent( 6010 );
			AddComponent( ac, 1, -3, 0 );

			ac = new AddonComponent( 6006 );
			AddComponent( ac, 2, 5, 0 );

			ac = new AddonComponent( 6006 );
			AddComponent( ac, -3, 2, 0 );

			ac = new AddonComponent( 6006 );
			AddComponent( ac, 4, -3, 0 );

			ac = new AddonComponent( 6004 );
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 6002 );
			AddComponent( ac, 5, 0, 0 );

			ac = new AddonComponent( 4968 );
			AddComponent( ac, 3, 3, 0 );

			ac = new AddonComponent( 4968 );
			AddComponent( ac, 3, -2, 0 );

			ac = new AddonComponent( 6018 );
			AddComponent( ac, 2, -4, 0 );

			ac = new AddonComponent( 6018 );
			AddComponent( ac, 1, -4, 0 );

			ac = new AddonComponent( 6018 );
			AddComponent( ac, 0, -4, 0 );

			ac = new AddonComponent( 6018 );
			AddComponent( ac, -1, -4, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, 2, -4, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, 1, -4, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, 0, -4, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, -1, -4, 0 );

			ac = new AddonComponent( 6021 );
			AddComponent( ac, 5, 2, 0 );

			ac = new AddonComponent( 6021 );
			AddComponent( ac, 5, 1, 0 );

			ac = new AddonComponent( 6021 );
			AddComponent( ac, 5, 0, 0 );

			ac = new AddonComponent( 6021 );
			AddComponent( ac, 5, -1, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, -1, 5, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, 2, 5, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, 1, 5, 0 );

			ac = new AddonComponent( 6020 );
			AddComponent( ac, 0, 5, 0 );

			ac = new AddonComponent( 6025 );
			AddComponent( ac, 3, 4, 0 );

			ac = new AddonComponent( 6025 );
			AddComponent( ac, 4, 3, 0 );

			ac = new AddonComponent( 6022 );
			AddComponent( ac, -2, 4, 0 );

			ac = new AddonComponent( 6022 );
			AddComponent( ac, -3, 3, 0 );

			ac = new AddonComponent( 6024 );
			AddComponent( ac, 4, -2, 0 );

			ac = new AddonComponent( 6024 );
			AddComponent( ac, 3, -3, 0 );

			ac = new AddonComponent( 6023 );
			AddComponent( ac, -3, -2, 0 );

			ac = new AddonComponent( 6023 );
			AddComponent( ac, -2, -3, 0 );

			ac = new AddonComponent( 14741 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 3, 0, 12 );

			ac = new AddonComponent( 14741 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 14741 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 2, 0 );

			ac = new AddonComponent( 14741 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, -1, 0, 0 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, -1, 1, 0 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 3388 );
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 3388 );
			AddComponent( ac, -1, 0, 0 );

			ac = new AddonComponent( 3388 );
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 3389 );
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 3388 );
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 3388 );
			AddComponent( ac, 2, -1, 2 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, 2, -1, 2 );

			ac = new AddonComponent( 3387 );
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 3, -1, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 3, -2, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 2, -2, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 1, -1, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 1, -2, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 0, -1, 0 );

			ac = new AddonComponent( 7066 );
			AddComponent( ac, 0, -2, 0 );

			ac = new AddonComponent( 7065 );
			AddComponent( ac, 3, -1, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -3, 3, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -3, 2, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -3, 1, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -3, 0, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -3, -1, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -3, -2, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 3, 4, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 2, 4, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 1, 4, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 0, 4, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -1, 4, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -2, 4, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 4, 3, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 4, 2, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 4, 1, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 4, 0, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 4, -1, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 4, -2, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 3, -3, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 2, -3, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 1, -3, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, 0, -3, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -1, -3, 0 );

			ac = new AddonComponent( 12789 );
			AddComponent( ac, -2, -3, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 3, 3, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 3, 1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 3, -1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 3, -2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 2, -2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 1, 2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 1, -1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 1, -2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 0, 3, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 0, 2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 0, 1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 0, 0, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 0, -1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, 0, -2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -1, 2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -1, 1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -1, 0, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -1, -1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -1, -2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -2, 3, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -2, 2, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -2, 1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -2, 0, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -2, -1, 0 );

			ac = new AddonComponent( 12795 );
			AddComponent( ac, -2, -2, 0 );


		}
		public BonfireAddon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class BonfireAddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new BonfireAddon();}}
		[Constructable]
		public BonfireAddonDeed(){Name = "Bonfire";}
		public BonfireAddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}