/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GypsyVardoWhiteNSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GypsyVardoWhiteNSAddonDeed();
			}
		}

		[ Constructable ]
		public GypsyVardoWhiteNSAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 5710 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 5710 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 5717 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 5710 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 5710 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, -3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, -2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, -1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, 1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, 2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, 3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, -1, 4, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, -3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, -2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, -1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, 1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, 2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, 3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 0, 4, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, -3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, -2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, -1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, 1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, 2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, 3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 1, 4, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, -3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, -2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, 1, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, 2, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, 3, 5 );
			ac = new AddonComponent( 2000 );
			AddComponent( ac, 2, 4, 5 );
			ac = new AddonComponent( 19 );
			AddComponent( ac, -2, -4, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, -3, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, -2, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, -1, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, 0, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, 1, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, 2, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, 3, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, -2, 4, 6 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, -1, -4, 6 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, 0, -4, 6 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, 1, -4, 6 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, 2, -4, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, 2, -3, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, 2, -2, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, 2, -1, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, 2, 0, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, 2, 1, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, 2, 2, 6 );
			ac = new AddonComponent( 17 );
			AddComponent( ac, 2, 3, 6 );
			ac = new AddonComponent( 16 );
			AddComponent( ac, 2, 4, 6 );
			ac = new AddonComponent( 18 );
			AddComponent( ac, -1, 4, 6 );
			ac = new AddonComponent( 875 );
			AddComponent( ac, -2, -4, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, -3, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, -2, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, -1, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, 0, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, 1, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, 2, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, 3, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, -2, 4, 12 );
			ac = new AddonComponent( 881 );
			AddComponent( ac, -1, -4, 12 );
			ac = new AddonComponent( 881 );
			AddComponent( ac, 0, -4, 12 );
			ac = new AddonComponent( 881 );
			AddComponent( ac, 1, -4, 12 );
			ac = new AddonComponent( 881 );
			AddComponent( ac, 2, -4, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, -3, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, -2, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, -1, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, 0, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, 1, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, 2, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, 3, 12 );
			ac = new AddonComponent( 880 );
			AddComponent( ac, 2, 4, 12 );
			ac = new AddonComponent( 881 );
			AddComponent( ac, 2, 4, 12 );
			ac = new AddonComponent( 881 );
			AddComponent( ac, -1, 4, 12 );
			ac = new AddonComponent( 2204 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 2204 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 1633 );
			AddComponent( ac, 2, 3, 27 );
			ac = new AddonComponent( 1633 );
			AddComponent( ac, 2, 2, 27 );
			ac = new AddonComponent( 1633 );
			AddComponent( ac, 2, 1, 27 );
			ac = new AddonComponent( 1633 );
			AddComponent( ac, 2, 0, 27 );
			ac = new AddonComponent( 1633 );
			AddComponent( ac, 2, -1, 27 );
			ac = new AddonComponent( 1633 );
			AddComponent( ac, 2, -2, 27 );
			ac = new AddonComponent( 1630 );
			AddComponent( ac, -1, -2, 27 );
			ac = new AddonComponent( 1630 );
			AddComponent( ac, -1, -1, 27 );
			ac = new AddonComponent( 1630 );
			AddComponent( ac, -1, 0, 27 );
			ac = new AddonComponent( 1630 );
			AddComponent( ac, -1, 1, 27 );
			ac = new AddonComponent( 1630 );
			AddComponent( ac, -1, 2, 27 );
			ac = new AddonComponent( 1630 );
			AddComponent( ac, -1, 3, 27 );
			ac = new AddonComponent( 1631 );
			AddComponent( ac, 1, -3, 27 );
			ac = new AddonComponent( 1631 );
			AddComponent( ac, 0, -3, 27 );
			ac = new AddonComponent( 1632 );
			AddComponent( ac, 1, 4, 27 );
			ac = new AddonComponent( 1632 );
			AddComponent( ac, 0, 4, 27 );
			ac = new AddonComponent( 1651 );
			AddComponent( ac, 1, 1, 30 );
			ac = new AddonComponent( 1651 );
			AddComponent( ac, 1, 0, 30 );
			ac = new AddonComponent( 1651 );
			AddComponent( ac, 1, 2, 30 );
			ac = new AddonComponent( 1651 );
			AddComponent( ac, 1, -1, 30 );
			ac = new AddonComponent( 1652 );
			AddComponent( ac, 0, 2, 30 );
			ac = new AddonComponent( 1652 );
			AddComponent( ac, 0, 1, 30 );
			ac = new AddonComponent( 1652 );
			AddComponent( ac, 0, 0, 30 );
			ac = new AddonComponent( 1652 );
			AddComponent( ac, 0, -1, 30 );
			ac = new AddonComponent( 1635 );
			AddComponent( ac, 1, 3, 30 );
			ac = new AddonComponent( 1635 );
			AddComponent( ac, 2, 4, 27 );
			ac = new AddonComponent( 1638 );
			AddComponent( ac, 0, 3, 30 );
			ac = new AddonComponent( 1638 );
			AddComponent( ac, -1, 4, 27 );
			ac = new AddonComponent( 1637 );
			AddComponent( ac, -1, -3, 27 );
			ac = new AddonComponent( 1637 );
			AddComponent( ac, 0, -2, 30 );
			ac = new AddonComponent( 1636 );
			AddComponent( ac, 1, -2, 30 );
			ac = new AddonComponent( 1636 );
			AddComponent( ac, 2, -3, 27 );

		}

		public GypsyVardoWhiteNSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GypsyVardoWhiteNSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GypsyVardoWhiteNSAddon();
			}
		}

		[Constructable]
		public GypsyVardoWhiteNSAddonDeed()
		{
			Name = "GypsyVardoWhiteNS";
		}

		public GypsyVardoWhiteNSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}