// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class HalloweenMinotaurYardAddon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new HalloweenMinotaurYardAddonDeed();}}
		[ Constructable ]
		public HalloweenMinotaurYardAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, -2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, -1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 0, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, -2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, -1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 0, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, -2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, -1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 0, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, -2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, -1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, -2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, -2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, -1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, 0, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, 1, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, 2, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 3, 3, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -2, 3, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 0, 3, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 1, 3, 0 );

			ac = new AddonComponent( 7385 );
			AddComponent( ac, 2, 3, 0 );

			ac = new AddonComponent( 7384 );
			AddComponent( ac, 4, 3, 0 );

			ac = new AddonComponent( 7384 );
			AddComponent( ac, 4, 1, 0 );

			ac = new AddonComponent( 7384 );
			AddComponent( ac, 4, -1, 0 );

			ac = new AddonComponent( 7383 );
			AddComponent( ac, 4, 2, 0 );

			ac = new AddonComponent( 7383 );
			AddComponent( ac, 4, 0, 0 );

			ac = new AddonComponent( 7383 );
			AddComponent( ac, 4, -2, 0 );

			ac = new AddonComponent( 7382 );
			AddComponent( ac, -2, -3, 0 );

			ac = new AddonComponent( 7382 );
			AddComponent( ac, 0, -3, 0 );

			ac = new AddonComponent( 7382 );
			AddComponent( ac, 1, -3, 0 );

			ac = new AddonComponent( 7382 );
			AddComponent( ac, 3, -3, 0 );

			ac = new AddonComponent( 7381 );
			AddComponent( ac, -1, -3, 0 );

			ac = new AddonComponent( 7381 );
			AddComponent( ac, 2, -3, 0 );

			ac = new AddonComponent( 7380 );
			AddComponent( ac, 3, 4, 0 );

			ac = new AddonComponent( 7380 );
			AddComponent( ac, 1, 4, 0 );

			ac = new AddonComponent( 7380 );
			AddComponent( ac, -1, 4, 0 );

			ac = new AddonComponent( 7379 );
			AddComponent( ac, 2, 4, 0 );

			ac = new AddonComponent( 7379 );
			AddComponent( ac, 0, 4, 0 );

			ac = new AddonComponent( 7379 );
			AddComponent( ac, -2, 4, 0 );

			ac = new AddonComponent( 7378 );
			AddComponent( ac, -3, 2, 0 );

			ac = new AddonComponent( 7378 );
			AddComponent( ac, -3, 0, 0 );

			ac = new AddonComponent( 7378 );
			AddComponent( ac, -3, -2, 0 );

			ac = new AddonComponent( 7377 );
			AddComponent( ac, -3, -1, 0 );

			ac = new AddonComponent( 7377 );
			AddComponent( ac, -3, 1, 0 );

			ac = new AddonComponent( 7377 );
			AddComponent( ac, -3, 3, 0 );

			ac = new AddonComponent( 7376 );
			AddComponent( ac, 4, -3, 0 );

			ac = new AddonComponent( 7375 );
			AddComponent( ac, -3, -3, 0 );

			ac = new AddonComponent( 7374 );
			AddComponent( ac, 4, 4, 0 );

			ac = new AddonComponent( 7373 );
			AddComponent( ac, -3, 4, 0 );

			ac = new AddonComponent( 12396 );
			ac.Hue = 1900;
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 12397 );
			AddComponent( ac, 0, 1, 0 );

			ac = new AddonComponent( 12398 );
			ac.Hue = 1900;
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 8708 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 2, 0 );

			ac = new AddonComponent( 8700 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 2, 20 );

			ac = new AddonComponent( 6873 );
			AddComponent( ac, 1, 2, 0 );

			ac = new AddonComponent( 6872 );
			ac.Hue = 1150;
			AddComponent( ac, 2, 2, 0 );

			ac = new AddonComponent( 6874 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 2, 0 );

			ac = new AddonComponent( 6876 );
			AddComponent( ac, 2, 1, 0 );

			ac = new AddonComponent( 6876 );
			AddComponent( ac, 2, 0, 0 );

			ac = new AddonComponent( 6877 );
			ac.Hue = 1150;
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 6878 );
			ac.Hue = 1150;
			AddComponent( ac, 3, -1, 0 );

			ac = new AddonComponent( 6658 );
			ac.Hue = 1900;
			AddComponent( ac, 0, 3, 4 );

			ac = new AddonComponent( 4310 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 3, 0 );

			ac = new AddonComponent( 3813 );
			ac.Hue = 1150;
			AddComponent( ac, 0, 1, 0 );

			ac = new AddonComponent( 4307 );
			ac.Hue = 1150;
			AddComponent( ac, 1, -1, 0 );

			ac = new AddonComponent( 4453 );
			ac.Hue = 1900;
			AddComponent( ac, -2, 3, 0 );

			ac = new AddonComponent( 4456 );
			ac.Hue = 1900;
			AddComponent( ac, 1, -2, 1 );

			ac = new AddonComponent( 6928 );
			AddComponent( ac, 3, 3, 1 );

			ac = new AddonComponent( 6921 );
			AddComponent( ac, -2, 2, 1 );

			ac = new AddonComponent( 6922 );
			AddComponent( ac, 3, -2, 1 );

			ac = new AddonComponent( 6923 );
			AddComponent( ac, 2, -1, 0 );

			ac = new AddonComponent( 6923 );
			AddComponent( ac, 3, 1, 1 );

			ac = new AddonComponent( 6930 );
			ac.Hue = 1150;
			AddComponent( ac, -2, 2, 0 );

			ac = new AddonComponent( 6921 );
			AddComponent( ac, 2, 1, 2 );

			ac = new AddonComponent( 6937 );
			ac.Hue = 1150;
			AddComponent( ac, -1, 3, 0 );

			ac = new AddonComponent( 6937 );
			ac.Hue = 1150;
			AddComponent( ac, -1, -2, 0 );

			ac = new AddonComponent( 6938 );
			AddComponent( ac, -2, -2, 0 );

			ac = new AddonComponent( 4655 );
			AddComponent( ac, 2, -3, 0 );

			ac = new AddonComponent( 4650 );
			AddComponent( ac, 0, 4, 0 );


		}
		public HalloweenMinotaurYardAddon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class HalloweenMinotaurYardAddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new HalloweenMinotaurYardAddon();}}
		[Constructable]
		public HalloweenMinotaurYardAddonDeed(){Name = "HalloweenMinotaurYard";}
		public HalloweenMinotaurYardAddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}