
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class maginciafactionbaseAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4029, -1, 3, 4}, {4031, 5, -4, 4}, {4031, 5, 0, 4}// 1	2	3	
			, {4031, 5, -6, 4}, {4031, 5, -5, 4}, {4031, 5, -7, 4}// 4	5	6	
			, {4031, 5, 1, 4}, {4031, 5, -2, 4}, {4031, 5, -3, 4}// 7	8	9	
			, {4031, 5, -1, 4}, {4031, -1, 2, 4}, {2976, -4, 8, 0}// 10	11	12	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new maginciafactionbaseAddonDeed();
			}
		}

		[ Constructable ]
		public maginciafactionbaseAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public maginciafactionbaseAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class maginciafactionbaseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new maginciafactionbaseAddon();
			}
		}

		[Constructable]
		public maginciafactionbaseAddonDeed()
		{
			Name = "maginciafactionbase";
		}

		public maginciafactionbaseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}