// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class PottedColumbineFushiaAddon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new PottedColumbineFushiaAddonDeed();}}
		[ Constructable ]
		public PottedColumbineFushiaAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 4551 );
			ac.Name = "potted columbine";
			AddComponent( ac, 0, 0, 0 );

			ac = new AddonComponent( 3332 );
			ac.Name = "columbine";
			AddComponent( ac, 0, 0, 3 );

			ac = new AddonComponent( 7870 );
			ac.Hue = 21;
			ac.Name = "columbine";
			AddComponent( ac, 0, 0, 8 );


		}
		public PottedColumbineFushiaAddon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class PottedColumbineFushiaAddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new PottedColumbineFushiaAddon();}}
		[Constructable]
		public PottedColumbineFushiaAddonDeed(){Name = "PottedColumbineFushia";}
		public PottedColumbineFushiaAddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}