
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Stable_Small_1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {10349, -4, 1, 1}, {10349, -4, -1, 1}, {10343, -1, -1, 1}// 1	2	5	
			, {10343, -1, 0, 1}, {10343, -1, 1, 1}, {10339, -1, 1, 1}// 6	7	8	
			, {10339, -3, 1, 1}, {10339, 0, 1, 1}, {13001, -3, -1, 1}// 9	10	11	
			, {13001, -3, 0, 1}, {13001, -3, 1, 1}, {13001, -2, -1, 1}// 12	13	14	
			, {13001, -2, 0, 1}, {13001, -2, 1, 1}, {13001, -1, -1, 1}// 15	16	17	
			, {13001, -1, 0, 1}, {13001, -1, 1, 1}, {13001, 0, -1, 0}// 18	19	20	
			, {13001, 0, 0, 0}, {13001, 0, 1, 1}, {9963, -3, 2, 28}// 21	22	23	
			, {9963, -2, 2, 28}, {9963, -1, 2, 28}, {9963, 0, 2, 28}// 24	25	26	
			, {9962, -2, 1, 29}, {9962, -1, 1, 30}, {9962, 0, 1, 30}// 27	28	29	
			, {9962, -3, 1, 29}, {9964, -3, 0, 26}, {9964, -2, 0, 27}// 30	31	32	
			, {9964, -1, 0, 28}, {9964, 0, 0, 28}, {9964, -3, -1, 21}// 33	34	35	
			, {9964, -3, 0, 21}, {9964, -3, 1, 21}, {9964, -2, -1, 21}// 36	37	38	
			, {9964, -2, 0, 21}, {9964, -2, 1, 21}, {9964, -1, -1, 21}// 39	40	41	
			, {9964, -1, 0, 21}, {9964, -1, 1, 21}, {9964, 0, -1, 21}// 42	43	44	
			, {9964, 0, 0, 21}, {9964, 0, 1, 21}, {10338, -2, -2, 1}// 45	46	47	
			, {10338, -1, -2, 1}, {10349, 3, 1, 1}, {10349, 3, -1, 1}// 49	50	51	
			, {10339, 1, 1, 1}, {10339, 3, 1, 1}, {13001, 1, -1, 0}// 53	54	55	
			, {13001, 1, 0, 0}, {13001, 1, 1, 1}, {13001, 2, -1, 1}// 56	57	58	
			, {13001, 2, 0, 1}, {13001, 2, 1, 1}, {13001, 3, -1, 1}// 59	60	61	
			, {13001, 3, 0, 1}, {13001, 3, 1, 1}, {9963, 1, 2, 28}// 62	63	64	
			, {9963, 2, 2, 28}, {9963, 3, 2, 28}, {9963, 4, 2, 29}// 65	66	67	
			, {9962, 1, 1, 30}, {9962, 2, 1, 30}, {9962, 3, 1, 31}// 68	69	70	
			, {9962, 4, 1, 31}, {9964, 1, 0, 27}, {9964, 2, 0, 28}// 71	72	73	
			, {9964, 3, 0, 28}, {9964, 4, 0, 27}, {9964, 1, -1, 21}// 74	75	76	
			, {9964, 1, 0, 21}, {9964, 1, 1, 21}, {9964, 2, -1, 21}// 77	78	79	
			, {9964, 2, 0, 21}, {9964, 2, 1, 21}, {9964, 4, -1, 22}// 80	81	82	
			, {9964, 3, -1, 21}, {9964, 3, 0, 21}, {9964, 3, 1, 21}// 83	84	85	
			, {10338, 1, -2, 1}, {10338, 2, -2, 1}// 86	87	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Stable_Small_1AddonDeed();
			}
		}

		[ Constructable ]
		public Stable_Small_1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 10348, -3, -2, 1, 0, 1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 10345, -4, 0, 1, 0, 1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 10341, 0, -2, 1, 0, 1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 10345, 3, 0, 1, 0, 1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 10341, 3, -2, 1, 0, 1, "", 1);// 88

		}

		public Stable_Small_1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Stable_Small_1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Stable_Small_1Addon();
			}
		}

		[Constructable]
		public Stable_Small_1AddonDeed()
		{
			Name = "Stable_Small_1";
		}

		public Stable_Small_1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}