/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class tikibarAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new tikibarAddonDeed();
			}
		}

		[ Constructable ]
		public tikibarAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 1280 );
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 2445 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2602 );
			ac.Hue = 1525;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 423 );
			ac.Hue = 1436;
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 424 );
			ac.Hue = 1436;
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 423 );
			ac.Hue = 1436;
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 425 );
			ac.Hue = 1436;
			AddComponent( ac, -4, -1, 0 );
			ac = new AddonComponent( 425 );
			ac.Hue = 1436;
			AddComponent( ac, -4, 0, 0 );
			ac = new AddonComponent( 425 );
			ac.Hue = 1436;
			AddComponent( ac, -4, 1, 0 );
			ac = new AddonComponent( 425 );
			ac.Hue = 1436;
			AddComponent( ac, -4, 2, 0 );
			ac = new AddonComponent( 425 );
			ac.Hue = 1436;
			AddComponent( ac, -4, 3, 0 );
			ac = new AddonComponent( 425 );
			ac.Hue = 1436;
			AddComponent( ac, -4, 4, 0 );
			ac = new AddonComponent( 4067 );
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 4068 );
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 4067 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1218 );
			ac.Hue = 1436;
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1218 );
			ac.Hue = 1436;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 1218 );
			ac.Hue = 1436;
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 1218 );
			ac.Hue = 1436;
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 1218 );
			ac.Hue = 1436;
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 1218 );
			ac.Hue = 1436;
			AddComponent( ac, -3, 4, 0 );
			ac = new AddonComponent( 4553 );
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, -4, -2, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 4, -3, 0 );
			ac = new AddonComponent( 4592 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 4593 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 3221 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 3221 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6419 );
			ac.Hue = 1525;
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 6424 );
			ac.Hue = 1525;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6424 );
			ac.Hue = 1525;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6427 );
			ac.Hue = 1525;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 6431 );
			ac.Hue = 1525;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6417 );
			ac.Hue = 1525;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6871 );
			AddComponent( ac, -1, 0, 12 );
			ac = new AddonComponent( 2456 );
			AddComponent( ac, 0, 1, 8 );
			ac = new AddonComponent( 2542 );
			AddComponent( ac, 0, 2, 8 );
			ac = new AddonComponent( 6465 );
			AddComponent( ac, -1, 3, 6 );
			ac = new AddonComponent( 2465 );
			AddComponent( ac, 0, 3, 11 );
			ac = new AddonComponent( 4007 );
			AddComponent( ac, 0, 0, 8 );
			ac = new AddonComponent( 2602 );
			ac.Hue = 1862;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2602 );
			ac.Hue = 1862;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, -1, 4, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 0, 4, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 1, 4, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 1217 );
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 1217 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 4, 1, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 1217 );
			ac.Hue = 1436;
			AddComponent( ac, 4, 4, 0 );
			ac = new AddonComponent( 6416 );
			ac.Hue = 1525;
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 6416 );
			ac.Hue = 1525;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 6417 );
			ac.Hue = 1525;
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 6417 );
			ac.Hue = 1525;
			AddComponent( ac, 4, 0, 0 );
			ac = new AddonComponent( 6418 );
			ac.Hue = 1525;
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 6418 );
			ac.Hue = 1525;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 2602 );
			ac.Hue = 1525;
			AddComponent( ac, 2, 4, 0 );
			ac = new AddonComponent( 2602 );
			ac.Hue = 1525;
			AddComponent( ac, 4, 2, 0 );
			ac = new AddonComponent( 2602 );
			ac.Hue = 1525;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2602 );
			ac.Hue = 1525;
			AddComponent( ac, 4, -1, 0 );
			ac = new AddonComponent( 2453 );
			AddComponent( ac, 3, 4, 8 );
			ac = new AddonComponent( 2453 );
			AddComponent( ac, 4, 3, 8 );
			ac = new AddonComponent( 2453 );
			AddComponent( ac, 3, 1, 8 );
			ac = new AddonComponent( 2453 );
			AddComponent( ac, 4, 0, 8 );
			ac = new AddonComponent( 4099 );
			AddComponent( ac, 4, 4, 4 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 1280 );
			AddComponent( ac, 4, -2, 0 );

		}

		public tikibarAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class tikibarAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new tikibarAddon();
			}
		}

		[Constructable]
		public tikibarAddonDeed()
		{
			Name = "tikibar";
		}

		public tikibarAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}