
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TimSandFireCornerAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {351, -1, 2, 19}, {374, 2, 0, 19}, {360, 1, 0, 29}// 1	2	3	
			, {4995, 1, 1, 19}, {351, -1, 1, 19}, {4995, 1, 0, 19}// 4	5	6	
			, {351, -1, 0, 19}, {4995, 0, 0, 19}, {4995, 0, 1, 19}// 7	9	10	
			, {374, 0, 2, 19}, {360, 0, 1, 29}, {933, 1, 0, 0}// 11	12	13	
			, {933, 1, 0, 10}, {933, 1, 0, 15}, {933, 1, 0, 5}// 14	16	17	
			, {933, 0, 1, 16}, {933, 0, 1, 6}, {933, 0, 1, 11}// 18	20	21	
			, {933, 0, 0, 11}, {933, 0, 1, 1}, {933, 0, 0, 1}// 22	23	24	
			, {933, 0, 0, 16}, {933, 0, 0, 6}, {352, 2, -1, 19}// 27	28	31	
			, {352, 0, -1, 19}, {353, -1, -1, 19}, {352, 1, -1, 19}// 32	33	34	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TimSandFireCornerAddonDeed();
			}
		}

		[ Constructable ]
		public TimSandFireCornerAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 6587, 0, 0, 17, 0, 1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 6571, 1, 0, 23, 0, 29, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 6587, 0, 1, 22, 0, 2, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 6571, 0, 0, 24, 0, 29, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 6587, 0, 0, 22, 0, 2, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 6571, 0, 1, 24, 0, 29, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 6587, 1, 0, 21, 0, 2, "", 1);// 30

		}

		public TimSandFireCornerAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TimSandFireCornerAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TimSandFireCornerAddon();
			}
		}

		[Constructable]
		public TimSandFireCornerAddonDeed()
		{
			Name = "TimSandFireCorner";
		}

		public TimSandFireCornerAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}