
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CustomRackGoreAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {4690, 0, 1, 0}, {4689, 1, 1, 0}, {4693, -1, 1, 0}// 1	2	3	
			, {4688, 1, 0, 0}, {5742, 0, 0, 3}, {7392, 1, 1, 5}// 4	5	6	
			, {4692, -1, 0, 0}, {4691, 0, 0, 0}, {4651, 1, 1, 3}// 7	8	9	
			, {4687, 2, 0, 0}, {6935, 2, 0, 3}, {4686, 2, 1, 0}// 10	11	12	
			, {4652, 2, 1, 3}// 13	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CustomRackGoreAddonDeed();
			}
		}

		[ Constructable ]
		public CustomRackGoreAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CustomRackGoreAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CustomRackGoreAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CustomRackGoreAddon();
			}
		}

		[Constructable]
		public CustomRackGoreAddonDeed()
		{
			Name = "CustomRackGore";
		}

		public CustomRackGoreAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}