
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class Big2DisplayCaseAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2720, 4, -2, 3}, {2720, 3, -2, 3}, {2720, 2, -2, 3}// 1	2	3	
			, {2720, 1, -2, 3}, {2720, 0, -2, 3}, {2720, -1, -2, 3}// 4	5	6	
			, {2720, -2, -2, 3}, {2719, -3, -1, 3}, {2719, -3, 0, 3}// 7	8	9	
			, {2719, -3, 1, 3}, {2719, -3, 2, 3}, {2719, -3, 3, 3}// 10	11	12	
			, {2723, -3, -2, 3}, {2831, 0, -1, 0}, {2831, 0, 0, 0}// 13	14	15	
			, {2831, -1, -1, 0}, {2831, -1, 0, 0}, {2831, 0, 1, 0}// 16	17	18	
			, {2831, -1, 1, 0}, {2831, -2, -1, 0}, {2831, -2, 0, 0}// 19	20	21	
			, {2831, -2, 1, 0}, {2831, 1, -1, 0}, {2831, 1, 0, 0}// 22	23	24	
			, {2831, 1, 1, 0}, {2831, 2, -1, 0}, {2831, 2, 0, 0}// 25	26	27	
			, {2831, 2, 1, 0}, {2831, 3, -1, 0}, {2831, 3, 0, 0}// 28	29	30	
			, {2831, 3, 1, 0}, {2831, 4, -1, 0}, {2831, 4, 0, 0}// 31	32	33	
			, {2831, 4, 1, 0}, {2831, 4, 2, 0}, {2831, 3, 2, 0}// 34	35	36	
			, {2831, 2, 2, 0}, {2831, 1, 2, 0}, {2831, 0, 2, 0}// 37	38	39	
			, {2831, -1, 2, 0}, {2831, 4, 3, 0}, {2831, 3, 3, 0}// 40	41	42	
			, {2831, 2, 3, 0}, {2831, 1, 3, 0}, {2831, 0, 3, 0}// 43	44	45	
			, {2831, -1, 3, 0}, {2831, -2, 2, 0}, {2831, -2, 3, 0}// 46	47	48	
			, {2839, -2, -2, 0}, {2839, -1, -2, 0}, {2839, 0, -2, 0}// 49	50	51	
			, {2839, 2, -2, 0}, {2839, 1, -2, 0}, {2839, 3, -2, 0}// 52	53	54	
			, {2839, 4, -2, 0}, {2838, -3, 3, 0}, {2838, -3, 2, 0}// 55	56	57	
			, {2838, -3, 1, 0}, {2838, -3, 0, 0}, {2838, -3, -1, 0}// 58	59	60	
			, {2832, -3, -2, 0}// 61	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new Big2DisplayCaseAddonDeed();
			}
		}

		[ Constructable ]
		public Big2DisplayCaseAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public Big2DisplayCaseAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class Big2DisplayCaseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new Big2DisplayCaseAddon();
			}
		}

		[Constructable]
		public Big2DisplayCaseAddonDeed()
		{
			Name = "Big2DisplayCase";
		}

		public Big2DisplayCaseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}