
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BankWagonAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BankWagonAddonDeed();
			}
		}

		[ Constructable ]
		public BankWagonAddon()
		{



			AddComplexComponent( (BaseAddon) this, 5799, 1, -3, 0, 0, -1, "Jail wagon", 1);// 1
			AddComplexComponent( (BaseAddon) this, 5799, 1, 0, 0, 0, -1, "Jail wagon", 1);// 2
			AddComplexComponent( (BaseAddon) this, 5794, -2, 0, 0, 0, -1, "Jail wagon", 1);// 3
			AddComplexComponent( (BaseAddon) this, 5794, -2, -3, 0, 0, -1, "Jail wagon", 1);// 4
			AddComplexComponent( (BaseAddon) this, 20722, -2, -3, 6, 0, -1, "Jail wagon", 1);// 5
			AddComplexComponent( (BaseAddon) this, 20722, -2, -2, 6, 0, -1, "Jail wagon", 1);// 6
			AddComplexComponent( (BaseAddon) this, 20722, -2, -1, 6, 0, -1, "Jail wagon", 1);// 7
			AddComplexComponent( (BaseAddon) this, 20722, -2, 0, 6, 0, -1, "Jail wagon", 1);// 8
			AddComplexComponent( (BaseAddon) this, 20722, -1, -3, 6, 0, -1, "Jail wagon", 1);// 9
			AddComplexComponent( (BaseAddon) this, 20722, -1, -2, 6, 0, -1, "Jail wagon", 1);// 10
			AddComplexComponent( (BaseAddon) this, 20722, -1, -1, 6, 0, -1, "Jail wagon", 1);// 11
			AddComplexComponent( (BaseAddon) this, 20722, -1, 0, 6, 0, -1, "Jail wagon", 1);// 12
			AddComplexComponent( (BaseAddon) this, 20722, -1, 1, 6, 0, -1, "Jail wagon", 1);// 13
			AddComplexComponent( (BaseAddon) this, 20722, 0, -3, 6, 0, -1, "Jail wagon", 1);// 14
			AddComplexComponent( (BaseAddon) this, 20722, 0, -2, 6, 0, -1, "Jail wagon", 1);// 15
			AddComplexComponent( (BaseAddon) this, 20722, 0, -1, 6, 0, -1, "Jail wagon", 1);// 16
			AddComplexComponent( (BaseAddon) this, 20722, 0, 0, 6, 0, -1, "Jail wagon", 1);// 17
			AddComplexComponent( (BaseAddon) this, 20722, 0, 1, 6, 0, -1, "Jail wagon", 1);// 18
			AddComplexComponent( (BaseAddon) this, 20722, 1, -3, 6, 0, -1, "Jail wagon", 1);// 19
			AddComplexComponent( (BaseAddon) this, 20722, 1, -2, 6, 0, -1, "Jail wagon", 1);// 20
			AddComplexComponent( (BaseAddon) this, 20722, 1, -1, 6, 0, -1, "Jail wagon", 1);// 21
			AddComplexComponent( (BaseAddon) this, 20722, 1, 0, 6, 0, -1, "Jail wagon", 1);// 22
			AddComplexComponent( (BaseAddon) this, 20722, 1, 1, 6, 0, -1, "Jail wagon", 1);// 23
			AddComplexComponent( (BaseAddon) this, 20797, 1, -3, 6, 0, -1, "Jail wagon", 1);// 24
			AddComplexComponent( (BaseAddon) this, 20797, 1, -1, 6, 0, -1, "Jail wagon", 1);// 25
			AddComplexComponent( (BaseAddon) this, 20794, -1, 0, 6, 0, -1, "Jail wagon", 1);// 26
			AddComplexComponent( (BaseAddon) this, 20792, 1, -2, 6, 0, -1, "Jail wagon", 1);// 27
			AddComplexComponent( (BaseAddon) this, 20792, -2, -2, 6, 0, -1, "Jail wagon", 1);// 28
			AddComplexComponent( (BaseAddon) this, 20797, -2, -3, 6, 0, -1, "Jail wagon", 1);// 29
			AddComplexComponent( (BaseAddon) this, 20797, -2, 0, 6, 0, -1, "Jail wagon", 1);// 30
			AddComplexComponent( (BaseAddon) this, 20797, -2, -1, 6, 0, -1, "Jail wagon", 1);// 31
			AddComplexComponent( (BaseAddon) this, 20778, 1, 0, 6, 0, -1, "Jail wagon", 1);// 32
			AddComplexComponent( (BaseAddon) this, 20794, 1, -4, 6, 0, -1, "Jail wagon", 1);// 33
			AddComplexComponent( (BaseAddon) this, 20794, -1, -4, 6, 0, -1, "Jail wagon", 1);// 34
			AddComplexComponent( (BaseAddon) this, 20775, -2, -4, 6, 0, -1, "Jail wagon", 1);// 35
			AddComplexComponent( (BaseAddon) this, 15871, -2, 1, 6, 2020, -1, "Jail wagon", 1);// 36
			AddComplexComponent( (BaseAddon) this, 15871, 0, 1, 6, 2020, -1, "Jail wagon", 1);// 37
			AddComplexComponent( (BaseAddon) this, 15871, 1, 1, 6, 2020, -1, "Jail wagon", 1);// 38
			AddComplexComponent( (BaseAddon) this, 20722, -1, -3, 26, 0, -1, "Jail wagon", 1);// 39
			AddComplexComponent( (BaseAddon) this, 20722, -1, -2, 26, 0, -1, "Jail wagon", 1);// 40
			AddComplexComponent( (BaseAddon) this, 20722, -1, -1, 26, 0, -1, "Jail wagon", 1);// 41
			AddComplexComponent( (BaseAddon) this, 20722, -1, 0, 26, 0, -1, "Jail wagon", 1);// 42
			AddComplexComponent( (BaseAddon) this, 20722, 0, -3, 26, 0, -1, "Jail wagon", 1);// 43
			AddComplexComponent( (BaseAddon) this, 20722, 0, -2, 26, 0, -1, "Jail wagon", 1);// 44
			AddComplexComponent( (BaseAddon) this, 20722, 0, -1, 26, 0, -1, "Jail wagon", 1);// 45
			AddComplexComponent( (BaseAddon) this, 20722, 0, 0, 26, 0, -1, "Jail wagon", 1);// 46
			AddComplexComponent( (BaseAddon) this, 20722, 1, -3, 26, 0, -1, "Jail wagon", 1);// 47
			AddComplexComponent( (BaseAddon) this, 20722, 1, -2, 26, 0, -1, "Jail wagon", 1);// 48
			AddComplexComponent( (BaseAddon) this, 20722, 1, -1, 26, 0, -1, "Jail wagon", 1);// 49
			AddComplexComponent( (BaseAddon) this, 20722, 1, 0, 26, 0, -1, "Jail wagon", 1);// 50
			AddComplexComponent( (BaseAddon) this, 20791, 0, -4, 6, 0, -1, "Jail wagon", 1);// 51
			AddComplexComponent( (BaseAddon) this, 20791, 0, 0, 6, 0, -1, "Jail wagon", 1);// 52
			AddComplexComponent( (BaseAddon) this, 20784, 1, -4, 26, 0, -1, "Jail wagon", 1);// 53
			AddComplexComponent( (BaseAddon) this, 20784, 0, -4, 26, 0, -1, "Jail wagon", 1);// 54
			AddComplexComponent( (BaseAddon) this, 20784, -1, -4, 26, 0, -1, "Jail wagon", 1);// 55
			AddComplexComponent( (BaseAddon) this, 20784, -1, 0, 26, 0, -1, "Jail wagon", 1);// 56
			AddComplexComponent( (BaseAddon) this, 20784, 0, 0, 26, 0, -1, "Jail wagon", 1);// 57
			AddComplexComponent( (BaseAddon) this, 20785, -2, 0, 26, 0, -1, "Jail wagon", 1);// 58
			AddComplexComponent( (BaseAddon) this, 20785, -2, -1, 26, 0, -1, "Jail wagon", 1);// 59
			AddComplexComponent( (BaseAddon) this, 20785, -2, -2, 26, 0, -1, "Jail wagon", 1);// 60
			AddComplexComponent( (BaseAddon) this, 20785, -2, -3, 26, 0, -1, "Jail wagon", 1);// 61
			AddComplexComponent( (BaseAddon) this, 20785, 1, -3, 26, 0, -1, "Jail wagon", 1);// 62
			AddComplexComponent( (BaseAddon) this, 20785, 1, -2, 26, 0, -1, "Jail wagon", 1);// 63
			AddComplexComponent( (BaseAddon) this, 20785, 1, -1, 26, 0, -1, "Jail wagon", 1);// 64
			AddComplexComponent( (BaseAddon) this, 20701, 1, 0, 26, 0, -1, "Jail wagon", 1);// 65
			AddComplexComponent( (BaseAddon) this, 20700, -2, -4, 26, 0, -1, "Jail wagon", 1);// 66
			AddComplexComponent( (BaseAddon) this, 10723, -1, 2, 3, 2020, -1, "hitch", 1);// 67
			AddComplexComponent( (BaseAddon) this, 10723, -1, 1, 3, 0, -1, "Jail wagon", 1);// 68
			AddComplexComponent( (BaseAddon) this, 10722, 0, 1, 3, 2020, -1, "hitch", 1);// 69
			AddComplexComponent( (BaseAddon) this, 10722, -1, 1, 3, 2020, -1, "hitch", 1);// 70
			AddComplexComponent( (BaseAddon) this, 10722, 0, 3, 3, 2020, -1, "hitch", 1);// 71
			AddComplexComponent( (BaseAddon) this, 10722, -1, 3, 3, 2020, -1, "hitch", 1);// 72
			AddComplexComponent( (BaseAddon) this, 10723, -1, 3, 3, 2020, -1, "hitch", 1);// 73
			AddComplexComponent( (BaseAddon) this, 10723, -1, 4, 3, 2020, -1, "hitch", 1);// 74
			AddComplexComponent( (BaseAddon) this, 10723, -1, 5, 3, 2020, -1, "hitch", 1);// 75
			AddComplexComponent( (BaseAddon) this, 16922, 1, 0, 36, 0, -1, "cannon", 1);// 76
			AddComplexComponent( (BaseAddon) this, 16922, -2, 0, 36, 0, -1, "cannon", 1);// 77
			AddComplexComponent( (BaseAddon) this, 16924, -2, -3, 36, 0, -1, "cannon", 1);// 78
			AddComplexComponent( (BaseAddon) this, 16924, 1, -3, 36, 0, -1, "cannon", 1);// 79
			AddComplexComponent( (BaseAddon) this, 16933, -1, -3, 26, 0, -1, "Cannon balls", 1);// 80
			AddComplexComponent( (BaseAddon) this, 16933, -1, -1, 26, 0, -1, "Cannon balls", 1);// 81
			AddComplexComponent( (BaseAddon) this, 16933, -1, -3, 31, 0, -1, "Cannon balls", 1);// 82
			AddComplexComponent( (BaseAddon) this, 16933, -1, -1, 31, 0, -1, "Cannon balls", 1);// 83
			AddComplexComponent( (BaseAddon) this, 16933, 0, -3, 26, 0, -1, "Cannon balls", 1);// 84
			AddComplexComponent( (BaseAddon) this, 2475, 0, -3, 6, 0, -1, "Jail wagon", 1);// 85
			AddComplexComponent( (BaseAddon) this, 2475, 0, -3, 10, 0, -1, "Jail wagon", 1);// 86
			AddComplexComponent( (BaseAddon) this, 2475, 0, -1, 16, 0, -1, "Jail wagon", 1);// 87
			AddComplexComponent( (BaseAddon) this, 2475, 0, -3, 16, 0, -1, "Jail wagon", 1);// 88
			AddComplexComponent( (BaseAddon) this, 2475, -1, -3, 6, 0, -1, "Jail wagon", 1);// 89
			AddComplexComponent( (BaseAddon) this, 2475, -1, -3, 11, 0, -1, "Jail wagon", 1);// 90
			AddComplexComponent( (BaseAddon) this, 2475, -1, -3, 16, 0, -1, "Jail wagon", 1);// 91
			AddComplexComponent( (BaseAddon) this, 2475, 0, -1, 6, 0, -1, "Jail wagon", 1);// 92
			AddComplexComponent( (BaseAddon) this, 2475, 0, -1, 11, 0, -1, "Jail wagon", 1);// 93
			AddComplexComponent( (BaseAddon) this, 2475, -1, -1, 6, 0, -1, "Jail wagon", 1);// 94
			AddComplexComponent( (BaseAddon) this, 2475, -1, -1, 11, 0, -1, "Jail wagon", 1);// 95
			AddComplexComponent( (BaseAddon) this, 2475, 0, -2, 6, 0, -1, "Jail wagon", 1);// 96
			AddComplexComponent( (BaseAddon) this, 2475, -1, -3, 6, 0, -1, "Jail wagon", 1);// 97
			AddComplexComponent( (BaseAddon) this, 2475, -1, -3, 6, 0, -1, "Jail wagon", 1);// 98
			AddComplexComponent( (BaseAddon) this, 2475, 0, -2, 11, 0, -1, "Jail wagon", 1);// 99
			AddComplexComponent( (BaseAddon) this, 2475, -1, -2, 16, 0, -1, "Jail wagon", 1);// 100
			AddComplexComponent( (BaseAddon) this, 2475, 0, -2, 16, 0, -1, "Jail wagon", 1);// 101
			AddComplexComponent( (BaseAddon) this, 2475, -1, -2, 6, 0, -1, "Jail wagon", 1);// 102
			AddComplexComponent( (BaseAddon) this, 2475, -1, -2, 11, 0, -1, "Jail wagon", 1);// 103
			AddComplexComponent( (BaseAddon) this, 2475, -1, -1, 16, 0, -1, "Jail wagon", 1);// 104
			AddComplexComponent( (BaseAddon) this, 20722, -2, 1, 6, 0, -1, "Jail wagon", 1);// 105
			AddComplexComponent( (BaseAddon) this, 2213, -1, 1, 9, 2020, -1, "Jail wagon", 1);// 106
			AddComplexComponent( (BaseAddon) this, 5510, -2, 0, 6, 0, -1, "Jail wagon", 1);// 107
			AddComplexComponent( (BaseAddon) this, 5565, 2, 0, 19, 2721, -1, "Jail wagon", 1);// 108
			AddComplexComponent( (BaseAddon) this, 5565, 2, -4, 18, 2721, -1, "Jail wagon", 1);// 109
			AddComplexComponent( (BaseAddon) this, 5564, -2, 1, 18, 2721, -1, "Jail wagon", 1);// 110
			AddComplexComponent( (BaseAddon) this, 5564, 1, 1, 19, 2721, -1, "Jail wagon", 1);// 111

		}

		public BankWagonAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BankWagonAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BankWagonAddon();
			}
		}

		[Constructable]
		public BankWagonAddonDeed()
		{
			Name = "BankWagon";
		}

		public BankWagonAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}