
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BrokenWagon2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18146, -2, -4, 5}, {18146, -1, -4, 5}, {18146, 1, -4, 5}// 1	2	3	
			, {18147, -3, -3, 5}, {18145, -3, -2, 5}, {18147, -3, -1, 5}// 4	5	6	
			, {18147, -3, 1, 5}, {7637, -2, -3, 6}, {5794, -2, -2, 0}// 7	8	9	
			, {7646, -2, -2, 6}, {7643, -2, -1, 6}, {7640, -2, 0, 6}// 10	11	12	
			, {7642, -2, 1, 6}, {5794, -2, 2, 0}, {7641, -2, 2, 6}// 13	14	15	
			, {18141, -2, 2, 5}, {10723, -2, 3, 0}, {7643, -1, -3, 6}// 16	18	19	
			, {7636, -1, -2, 6}, {4335, -1, -2, 6}, {7637, -1, 0, 6}// 20	21	22	
			, {12551, -1, -1, 6}, {7644, -1, 1, 6}, {7646, -1, 2, 6}// 23	24	25	
			, {10723, -1, 3, 0}, {10722, -1, 3, 0}, {10723, -1, 4, 0}// 27	28	29	
			, {7635, 0, -3, 6}, {7639, 0, -2, 6}, {7638, 0, -1, 6}// 30	31	32	
			, {4336, 0, -1, 6}, {7641, 0, 0, 6}, {7643, 0, 1, 6}// 33	34	35	
			, {7646, 0, 2, 6}, {18146, 0, 2, 6}, {10722, 0, 3, 0}// 36	37	39	
			, {10723, 0, 3, 0}, {7638, 1, -3, 6}, {18145, 1, -3, 5}// 40	41	42	
			, {5799, 1, -2, 0}, {7636, 1, -2, 6}, {18147, 1, -2, 5}// 43	44	45	
			, {7639, 1, -1, 6}, {18145, 1, -1, 5}, {7640, 1, 0, 6}// 46	47	48	
			, {7645, 1, 1, 6}, {18147, 1, 1, 5}, {5799, 1, 2, 0}// 49	50	51	
			, {7648, 1, 2, 6}, {18141, 1, 2, 5}, {18145, 1, 2, 6}// 52	53	54	
			, {4336, 2, -1, 0}, {4338, 2, -1, 0}, {25091, 2, 0, 0}// 56	57	58	
			, {4337, 2, 1, 0}, {4337, 3, -2, 0}, {3814, -2, -3, 6}// 59	60	61	
			, {3813, -1, 3, 6}// 62	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BrokenWagon2AddonDeed();
			}
		}

		[ Constructable ]
		public BrokenWagon2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 12531, -2, 3, 6, 2012, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 12525, 1, 3, 6, 2012, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 12523, 0, 3, 6, 2012, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 12537, -1, 3, 6, 2012, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 4306, 2, -2, 0, 1361, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 4311, -2, -1, 6, 1361, -1, "", 1);// 64

		}

		public BrokenWagon2Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BrokenWagon2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BrokenWagon2Addon();
			}
		}

		[Constructable]
		public BrokenWagon2AddonDeed()
		{
			Name = "BrokenWagon2";
		}

		public BrokenWagon2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}