
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class HayRideAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7733, 2, -1, 13}, {3892, 0, 0, 8}, {3892, 0, 1, 7}// 1	2	3	
			, {3892, 1, 2, 8}, {3892, 0, 2, 8}, {3892, -1, 2, 8}// 4	6	7	
			, {3892, -2, 2, 8}, {3892, -3, 1, 7}, {3892, -3, 0, 8}// 8	9	10	
			, {4150, -2, 0, 8}, {4150, 1, 0, 8}, {4150, 1, 0, 8}// 11	12	13	
			, {3893, 1, 0, 8}, {3893, 1, 2, 8}, {3893, 0, 1, 7}// 14	15	16	
			, {3893, 0, 0, 8}, {3893, -2, 2, 8}, {3893, -1, 2, 8}// 17	18	19	
			, {3892, 0, 1, 7}, {3892, -1, 1, 7}, {3892, 3, 0, 8}// 20	21	22	
			, {3892, -2, 1, 7}, {7733, 2, 2, 14}, {3893, -3, 2, 8}// 23	24	26	
			, {2860, -2, 2, 7}, {3893, -3, 0, 8}, {3893, -2, 0, 7}// 27	28	29	
			, {2860, 0, 0, 7}, {5831, -3, 0, 0}, {2145, -4, 0, 7}// 30	33	35	
			, {2860, 3, 2, 7}, {2860, 3, 1, 7}, {10722, 3, 1, 0}// 38	41	43	
			, {2860, 3, 0, 7}, {21, 2, 2, 7}, {1993, 2, 2, 6}// 44	51	52	
			, {1996, 2, 1, 6}, {21, 2, 1, 7}, {1994, 2, 0, 6}// 53	54	56	
			, {5831, 2, 0, 0}, {21, 2, 0, 7}, {1995, 1, 2, 6}// 57	58	62	
			, {1996, 1, 1, 6}, {1995, 1, 0, 6}, {2860, 1, 0, 7}// 64	65	66	
			, {1993, 0, 2, 6}, {2860, -1, 0, 7}, {1995, 0, 1, 6}// 67	68	69	
			, {1994, 0, 0, 6}, {2860, -1, 2, 7}, {1995, -1, 2, 6}// 70	72	73	
			, {1996, -1, 1, 6}, {1993, -1, 0, 6}, {1994, -2, 2, 6}// 74	75	76	
			, {1995, -2, 1, 6}, {1996, -2, 0, 6}, {1996, -3, 2, 6}// 77	78	81	
			, {1993, -3, 1, 6}, {1995, -3, 0, 6}, {2860, -3, 0, 7}// 83	84	86	
			, {2860, 1, 2, 7}, {2860, -2, 0, 7}, {2860, 0, 2, 7}// 87	88	89	
			, {2860, -3, 2, 7}, {3893, -1, 0, 8}, {3892, -1, 1, 8}// 93	94	95	
			, {3892, -2, 0, 8}, {3892, -1, 0, 8}, {3892, -3, 2, 8}// 96	97	98	
			, {3892, 1, 0, 8}, {3892, 3, 1, 9}, {3892, 3, 2, 9}// 99	100	101	
			, {3179, 0, 2, 9}, {3179, -2, -1, 13}, {3179, -2, 2, 9}// 107	108	109	
			, {3179, 2, 2, 17}, {3180, 0, -1, 13}// 110	111	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new HayRideAddonDeed();
			}
		}

		[ Constructable ]
		public HayRideAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2144, -3, -1, 7, 0, -1, "hay ride", 1);// 5
			AddComplexComponent( (BaseAddon) this, 7869, 2, 1, 7, 0, -1, "corn stalks", 1);// 25
			AddComplexComponent( (BaseAddon) this, 7869, 2, 2, 7, 0, -1, "corn stalks", 1);// 31
			AddComplexComponent( (BaseAddon) this, 7869, 2, 0, 7, 0, -1, "corn stalks", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2168, -4, 0, 7, 0, -1, "hay ride", 1);// 34
			AddComplexComponent( (BaseAddon) this, 2144, -1, 2, 8, 0, -1, "hay ride", 1);// 36
			AddComplexComponent( (BaseAddon) this, 2141, -2, 2, 8, 0, -1, "hay ride", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1996, 3, 2, 6, 0, -1, "hay ride", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1995, 3, 1, 6, 0, -1, "hay ride", 1);// 40
			AddComplexComponent( (BaseAddon) this, 10723, 3, 1, 0, 0, -1, "hay ride", 1);// 42
			AddComplexComponent( (BaseAddon) this, 10722, 3, 0, 0, 0, -1, "hay ride", 1);// 45
			AddComplexComponent( (BaseAddon) this, 10723, 3, 0, 0, 0, -1, "hay ride", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1994, 3, 0, 6, 0, -1, "hay ride", 1);// 47
			AddComplexComponent( (BaseAddon) this, 10722, 3, -1, 0, 0, -1, "hay ride", 1);// 48
			AddComplexComponent( (BaseAddon) this, 5836, 2, 2, 0, 0, -1, "hay ride", 1);// 49
			AddComplexComponent( (BaseAddon) this, 21, 2, 2, 12, 0, -1, "hay ride", 1);// 50
			AddComplexComponent( (BaseAddon) this, 21, 2, 1, 12, 0, -1, "hay ride", 1);// 55
			AddComplexComponent( (BaseAddon) this, 21, 2, 0, 12, 0, -1, "hay ride", 1);// 59
			AddComplexComponent( (BaseAddon) this, 2141, 0, -1, 7, 0, -1, "hay ride", 1);// 60
			AddComplexComponent( (BaseAddon) this, 2141, -2, -1, 7, 0, -1, "hay ride", 1);// 61
			AddComplexComponent( (BaseAddon) this, 2141, 2, 2, 8, 0, -1, "hay ride", 1);// 63
			AddComplexComponent( (BaseAddon) this, 2144, -1, -1, 7, 0, -1, "hay ride", 1);// 71
			AddComplexComponent( (BaseAddon) this, 2141, 2, -1, 7, 0, -1, "hay ride", 1);// 79
			AddComplexComponent( (BaseAddon) this, 2144, 1, 2, 8, 0, -1, "hay ride", 1);// 80
			AddComplexComponent( (BaseAddon) this, 5836, -3, 2, 0, 0, -1, "hay ride", 1);// 82
			AddComplexComponent( (BaseAddon) this, 2144, 1, -1, 7, 0, -1, "hay ride", 1);// 85
			AddComplexComponent( (BaseAddon) this, 2168, -4, 2, 7, 0, -1, "hay ride", 1);// 90
			AddComplexComponent( (BaseAddon) this, 2141, 0, 2, 8, 0, -1, "hay ride", 1);// 91
			AddComplexComponent( (BaseAddon) this, 2144, -3, 2, 8, 0, -1, "hay ride", 1);// 92
			AddComplexComponent( (BaseAddon) this, 2581, 2, -1, 9, 0, 0, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 2581, 2, 2, 12, 0, 0, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 3178, 2, 0, 14, 0, -1, "a carved pumpkin", 1);// 104
			AddComplexComponent( (BaseAddon) this, 3178, -4, 0, 11, 0, -1, "a carved pumpkin", 1);// 105
			AddComplexComponent( (BaseAddon) this, 3178, -4, 2, 11, 0, -1, "a carved pumpkin", 1);// 106
			AddComplexComponent( (BaseAddon) this, 10722, 5, 0, 0, 0, -1, "hay ride", 1);// 112
			AddComplexComponent( (BaseAddon) this, 10722, 4, 0, 0, 0, -1, "hay ride", 1);// 113

		}

		public HayRideAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class HayRideAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new HayRideAddon();
			}
		}

		[Constructable]
		public HayRideAddonDeed()
		{
			Name = "HayRide";
		}

		public HayRideAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}