
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LittleRedWagonAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LittleRedWagonAddonDeed();
			}
		}

		[ Constructable ]
		public LittleRedWagonAddon()
		{



			AddComplexComponent( (BaseAddon) this, 190, -2, 0, 2, 37, -1, "Little Red Wagon", 1);// 1
			AddComplexComponent( (BaseAddon) this, 191, -1, -1, 2, 37, -1, "Little Red Wagon", 1);// 2
			AddComplexComponent( (BaseAddon) this, 191, -1, 0, 2, 37, -1, "Little Red Wagon", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1217, -1, 0, 2, 37, -1, "Little Red Wagon", 1);// 4
			AddComplexComponent( (BaseAddon) this, 6277, -1, 0, 0, 0, -1, "Little Red Wagon", 1);// 5
			AddComplexComponent( (BaseAddon) this, 6277, -1, 1, 0, 0, -1, "Little Red Wagon", 1);// 6
			AddComplexComponent( (BaseAddon) this, 191, 0, -1, 2, 37, -1, "Little Red Wagon", 1);// 7
			AddComplexComponent( (BaseAddon) this, 191, 0, 0, 2, 37, -1, "Little Red Wagon", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1217, 0, 0, 2, 37, -1, "Little Red Wagon", 1);// 9
			AddComplexComponent( (BaseAddon) this, 191, 1, -1, 2, 37, -1, "Little Red Wagon", 1);// 10
			AddComplexComponent( (BaseAddon) this, 189, 1, 0, 2, 37, -1, "Little Red Wagon", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1217, 1, 0, 2, 37, -1, "Little Red Wagon", 1);// 12
			AddComplexComponent( (BaseAddon) this, 6277, 1, 0, 0, 0, -1, "Little Red Wagon", 1);// 13
			AddComplexComponent( (BaseAddon) this, 6277, 1, 1, 0, 0, -1, "Little Red Wagon", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6791, 2, 0, 0, 37, -1, "Little Red Wagon", 1);// 15

		}

		public LittleRedWagonAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LittleRedWagonAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LittleRedWagonAddon();
			}
		}

		[Constructable]
		public LittleRedWagonAddonDeed()
		{
			Name = "LittleRedWagon";
		}

		public LittleRedWagonAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}