
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WagonSouthAddonAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new WagonSouthAddonAddonDeed();
			}
		}

		[ Constructable ]
		public WagonSouthAddonAddon()
		{



			AddComplexComponent( (BaseAddon) this, 1998, 0, -1, 6, 0, -1, "Wagon", 1);// 1
			AddComplexComponent( (BaseAddon) this, 24, 2, 2, 10, 0, -1, "Wagon", 1);// 2
			AddComplexComponent( (BaseAddon) this, 24, 0, 2, 10, 0, -1, "Wagon", 1);// 3
			AddComplexComponent( (BaseAddon) this, 25, 2, -2, 7, 0, -1, "Wagon", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1999, 1, -1, 6, 0, -1, "Wagon", 1);// 5
			AddComplexComponent( (BaseAddon) this, 5794, 0, 2, 0, 0, -1, "Wagon", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2000, 1, 2, 6, 0, -1, "Wagon", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2000, 0, -3, 6, 0, -1, "Wagon", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2000, 1, 0, 6, 0, -1, "Wagon", 1);// 9
			AddComplexComponent( (BaseAddon) this, 21, -1, -3, 10, 0, -1, "Wagon", 1);// 10
			AddComplexComponent( (BaseAddon) this, 21, 2, -1, 10, 0, -1, "Wagon", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2000, 2, 1, 6, 0, -1, "Wagon", 1);// 12
			AddComplexComponent( (BaseAddon) this, 25, 2, -3, 7, 0, -1, "Wagon", 1);// 13
			AddComplexComponent( (BaseAddon) this, 21, -1, 0, 10, 0, -1, "Wagon", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1998, 2, 2, 6, 0, -1, "Wagon", 1);// 15
			AddComplexComponent( (BaseAddon) this, 25, -1, -3, 7, 0, -1, "Wagon", 1);// 16
			AddComplexComponent( (BaseAddon) this, 21, 2, 1, 10, 0, -1, "Wagon", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1997, 2, -1, 6, 0, -1, "Wagon", 1);// 18
			AddComplexComponent( (BaseAddon) this, 2000, 1, 3, 6, 0, -1, "Wagon", 1);// 19
			AddComplexComponent( (BaseAddon) this, 25, 2, 0, 7, 0, -1, "Wagon", 1);// 20
			AddComplexComponent( (BaseAddon) this, 21, -1, -1, 10, 0, -1, "Wagon", 1);// 21
			AddComplexComponent( (BaseAddon) this, 5794, 0, -3, 0, 0, -1, "Wagon", 1);// 22
			AddComplexComponent( (BaseAddon) this, 10723, 0, 3, 0, 0, -1, "Wagon", 1);// 23
			AddComplexComponent( (BaseAddon) this, 10722, 1, 3, 0, 0, -1, "wagon hitch", 1);// 24
			AddComplexComponent( (BaseAddon) this, 21, -1, -2, 10, 0, -1, "Wagon", 1);// 25
			AddComplexComponent( (BaseAddon) this, 24, 2, -4, 10, 0, -1, "Wagon", 1);// 26
			AddComplexComponent( (BaseAddon) this, 24, 0, -4, 10, 0, -1, "Wagon", 1);// 27
			AddComplexComponent( (BaseAddon) this, 24, 1, 2, 10, 0, -1, "Wagon", 1);// 28
			AddComplexComponent( (BaseAddon) this, 25, -1, -2, 7, 0, -1, "Wagon", 1);// 29
			AddComplexComponent( (BaseAddon) this, 2000, 0, 3, 6, 0, -1, "Wagon", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1999, 0, 1, 6, 0, -1, "Wagon", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1999, 2, -3, 6, 0, -1, "Wagon", 1);// 32
			AddComplexComponent( (BaseAddon) this, 21, 2, 0, 10, 0, -1, "Wagon", 1);// 33
			AddComplexComponent( (BaseAddon) this, 21, 2, 2, 10, 0, -1, "Wagon", 1);// 34
			AddComplexComponent( (BaseAddon) this, 25, -1, 0, 7, 0, -1, "Wagon", 1);// 35
			AddComplexComponent( (BaseAddon) this, 24, 2, -4, 7, 0, -1, "Wagon", 1);// 36
			AddComplexComponent( (BaseAddon) this, 21, 2, -2, 10, 0, -1, "Wagon", 1);// 37
			AddComplexComponent( (BaseAddon) this, 21, 2, -3, 10, 0, -1, "Wagon", 1);// 38
			AddComplexComponent( (BaseAddon) this, 21, -1, 2, 10, 0, -1, "Wagon", 1);// 39
			AddComplexComponent( (BaseAddon) this, 1997, 1, 1, 6, 0, -1, "Wagon", 1);// 40
			AddComplexComponent( (BaseAddon) this, 10723, 0, 5, 0, 0, -1, "wagon hitch", 1);// 41
			AddComplexComponent( (BaseAddon) this, 21, -1, 1, 10, 0, -1, "Wagon", 1);// 42
			AddComplexComponent( (BaseAddon) this, 25, -1, 1, 7, 0, -1, "Wagon", 1);// 43
			AddComplexComponent( (BaseAddon) this, 25, 2, 1, 7, 0, -1, "Wagon", 1);// 44
			AddComplexComponent( (BaseAddon) this, 24, 0, 2, 7, 0, -1, "Wagon", 1);// 45
			AddComplexComponent( (BaseAddon) this, 25, -1, 2, 7, 0, -1, "Wagon", 1);// 46
			AddComplexComponent( (BaseAddon) this, 24, 1, 2, 7, 0, -1, "Wagon", 1);// 47
			AddComplexComponent( (BaseAddon) this, 5799, 2, 2, 0, 0, -1, "wagon wheel", 1);// 48
			AddComplexComponent( (BaseAddon) this, 10723, -1, 3, 0, 0, -1, "Wagon", 1);// 49
			AddComplexComponent( (BaseAddon) this, 25, 2, -1, 7, 0, -1, "Wagon", 1);// 50
			AddComplexComponent( (BaseAddon) this, 24, 0, -4, 7, 0, -1, "Wagon", 1);// 51
			AddComplexComponent( (BaseAddon) this, 10723, 0, 4, 0, 0, -1, "wagon hitch", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1997, 0, 2, 6, 0, -1, "Wagon", 1);// 53
			AddComplexComponent( (BaseAddon) this, 10723, 1, 3, 0, 0, -1, "Wagon", 1);// 54
			AddComplexComponent( (BaseAddon) this, 5800, 2, -3, 0, 0, -1, "wagon wheel", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2000, 1, -3, 6, 0, -1, "Wagon", 1);// 56
			AddComplexComponent( (BaseAddon) this, 25, 2, 2, 7, 0, -1, "Wagon", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2861, 1, 3, 7, 0, -1, "wagon bench", 1);// 58
			AddComplexComponent( (BaseAddon) this, 10722, 0, 3, 0, 0, -1, "wagon hitch", 1);// 59
			AddComplexComponent( (BaseAddon) this, 24, 2, 2, 7, 0, -1, "Wagon", 1);// 60
			AddComplexComponent( (BaseAddon) this, 1997, 1, -2, 6, 0, -1, "Wagon", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1999, 0, -2, 6, 0, -1, "Wagon", 1);// 62
			AddComplexComponent( (BaseAddon) this, 25, -1, -1, 7, 0, -1, "Wagon", 1);// 63
			AddComplexComponent( (BaseAddon) this, 2000, 2, -2, 6, 0, -1, "Wagon", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1999, 2, 3, 6, 0, -1, "Wagon", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1998, 0, 0, 6, 0, -1, "Wagon", 1);// 66
			AddComplexComponent( (BaseAddon) this, 2861, 2, 3, 7, 0, -1, "wagon bench", 1);// 67
			AddComplexComponent( (BaseAddon) this, 2861, 0, 3, 7, 0, -1, "wagon bench", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1997, 2, 0, 6, 0, -1, "Wagon", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1851, 1, -4, 0, 0, -1, "Wagon", 1);// 70
			AddComplexComponent( (BaseAddon) this, 2188, -1, 2, 7, 0, 0, "a lamp", 1);// 71
			AddComplexComponent( (BaseAddon) this, 2188, 2, 2, 7, 0, 0, "a lamp", 1);// 72

		}

		public WagonSouthAddonAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class WagonSouthAddonAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new WagonSouthAddonAddon();
			}
		}

		[Constructable]
		public WagonSouthAddonAddonDeed()
		{
			Name = "WagonSouthAddon";
		}

		public WagonSouthAddonAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}