namespace Server.Services.ContainerSort
{
	public enum ItemSortType
	{
		Unknown = 0,
		AllOre = 1,
		IronOre = 2,
		DullCopperOre = 3,
		ShadowIronOre = 4,
		CopperOre = 5,
		BronzeOre = 6,
		GoldOre = 7,
		AgapiteOre = 8,
		VeriteOre = 9,
		ValoriteOre = 10,
		AllIgnots = 11,
		IronIngot = 12,
		DullCopperIngot = 13,
		ShadowIronIngot = 14,
		CopperIngot = 15,
		BronzeIngot = 16,
		GoldIngot = 17,
		AgapiteIngot = 18,
		VeriteIngot = 19,
		ValoriteIngot = 20,
		AllGems = 21,
		Amber = 22,
		Citrine = 23,
		Ruby = 24,
		Tourmaline = 25,
		Amethyst = 26,
		Emerald = 27,
		Sapphire = 28,
		StarSapphire = 29,
		Diamond = 30,
		PrismaticAmber = 31,
		BrilliantAmber = 32,
		BlueDiamond = 33,
		DarkSapphire = 34,
		EcruCitrine = 35,
		FireRuby = 36,
		PerfectEmerald = 37,
		Turquoise = 38,
		WhitePearl = 39,
		ArcaneGem = 40
	}
}
