
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CommodityBrokerStyle2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2592, 1, -2, 0}, {2967, 2, -2, 0}, {9253, 2, -1, 0}// 1	2	3	
			, {9255, -1, -1, 0}, {9271, 0, -1, 0}, {9271, 1, -1, 0}// 4	5	6	
			, {9254, -1, 2, 0}, {9256, 2, 2, 0}, {9266, -1, 1, 0}// 7	8	9	
			, {9266, -1, 0, 0}, {9271, 1, 2, 0}, {9271, 0, 2, 0}// 10	11	12	
			, {9272, 0, 1, 0}, {9272, 0, 0, 0}, {9272, 1, 1, 0}// 13	14	15	
			, {9272, 1, 0, 0}, {9268, 2, 1, 0}, {9268, 2, 0, 0}// 16	17	18	
			, {2963, -1, 1, 0}, {2964, -1, 0, 0}// 19	20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CommodityBrokerStyle2AddonDeed();
			}
		}

		[ Constructable ]
		public CommodityBrokerStyle2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public CommodityBrokerStyle2Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CommodityBrokerStyle2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CommodityBrokerStyle2Addon();
			}
		}

		[Constructable]
		public CommodityBrokerStyle2AddonDeed()
		{
			Name = "Commodity Broker Style 2 Deed";
		}

		public CommodityBrokerStyle2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}