
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GreyDrkFPSouth2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1315, 2, 1, 0}, {1315, 1, 1, 0}, {1315, 0, 1, 0}// 1	2	3	
			, {2598, 2, 0, 11}, {1822, 2, -1, 11}, {1822, 1, -1, 11}// 8	9	10	
			, {1822, 0, -1, 11}, {1993, 2, 0, 10}, {1993, 1, 0, 10}// 11	12	13	
			, {1993, 0, 0, 10}, {1993, 2, -1, 10}, {1993, 1, -1, 10}// 14	15	16	
			, {1993, 0, -1, 10}, {1822, 2, 0, 5}, {1822, 2, -1, 5}// 17	18	19	
			, {1822, 1, -1, 5}, {1822, 0, -1, 5}, {1822, 2, 0, 0}// 20	21	22	
			, {1822, 2, -1, 0}, {1822, 1, -1, 0}, {1822, 0, -1, 0}// 23	24	25	
			, {1315, 2, 0, 0}, {1315, 2, -1, 0}, {1315, 1, -1, 0}// 26	29	30	
			, {1315, 0, -1, 0}, {1315, -1, 1, 0}, {1315, -2, 1, 0}// 31	32	33	
			, {2598, -2, 0, 11}, {1822, -1, -1, 11}, {1822, -2, -1, 11}// 36	37	38	
			, {1993, -1, 0, 10}, {1993, -2, 0, 10}, {1993, -1, -1, 10}// 39	40	41	
			, {1993, -2, -1, 10}, {1822, -2, 0, 5}, {1822, -1, -1, 5}// 42	43	44	
			, {1822, -2, -1, 5}, {1822, -2, 0, 0}, {1822, -1, -1, 0}// 45	46	47	
			, {1822, -2, -1, 0}, {1315, -2, 0, 0}, {1315, -2, -1, 0}// 48	50	51	
			, {1315, -1, -1, 0}// 52	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GreyDrkFPSouth2AddonDeed();
			}
		}

		[ Constructable ]
		public GreyDrkFPSouth2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3555, 1, 0, 0, 0, 29, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3555, 1, 0, 3, 0, 29, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3555, 0, 0, 0, 0, 29, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3555, 0, 0, 3, 0, 29, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1315, 1, 0, 0, 1147, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1315, 0, 0, 0, 1147, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 3555, -1, 0, 0, 0, 29, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 3561, -1, 0, 3, 0, 2, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1315, -1, 0, 0, 1147, -1, "", 1);// 49

		}

		public GreyDrkFPSouth2Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GreyDrkFPSouth2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GreyDrkFPSouth2Addon();
			}
		}

		[Constructable]
		public GreyDrkFPSouth2AddonDeed()
		{
			Name = "GreyDrkFPSouth2";
		}

		public GreyDrkFPSouth2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}