
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class hex_FirepSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7138, 0, -1, 4}, {486, 1, 0, 4}, {486, -2, 0, 4}// 1	2	3	
			, {465, -2, -1, 4}, {465, 1, -1, 4}, {489, -1, -1, 21}// 4	5	6	
			, {489, 0, -1, 21}, {489, 1, -1, 18}, {489, -1, -1, 18}// 7	8	9	
			, {489, 0, -1, 18}, {7777, 0, 0, 9}, {7744, 1, 2, 4}// 10	13	14	
			, {7745, 1, 1, 4}, {7746, 1, 0, 4}, {7747, 0, 0, 4}// 15	16	17	
			, {7748, 0, 1, 4}, {7749, 0, 2, 4}, {7750, -1, 2, 4}// 18	19	20	
			, {7751, -1, 1, 4}, {7752, -1, 0, 4}, {464, -1, -2, 4}// 21	22	23	
			, {464, 0, -2, 4}, {464, 1, -2, 4}, {466, -2, -2, 4}// 24	25	26	
			, {470, -1, -1, 0}, {489, 1, -1, 21}, {1312, -2, 0, 4}// 27	28	29	
			, {1312, -1, 0, 4}, {1312, 0, 0, 4}, {1312, 1, 0, 4}// 30	31	32	
			, {1312, 2, 0, 4}, {1312, 2, -1, 4}, {1312, -2, -1, 4}// 33	34	35	
			, {1313, -1, -1, 4}, {1313, 0, -1, 4}, {1313, 1, -1, 4}// 36	37	38	
			, {2867, -1, 1, 4}, {4604, 0, 1, 4}, {487, 2, -1, 4}// 39	40	41	
			, {7712, 0, 2, 4}// 42	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new hex_FirepSouthAddonDeed();
			}
		}

		[ Constructable ]
		public hex_FirepSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 14732, 0, -1, 5, 0, 1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 14742, 0, -1, 7, 0, 1, "", 1);// 12

		}

		public hex_FirepSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class hex_FirepSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new hex_FirepSouthAddon();
			}
		}

		[Constructable]
		public hex_FirepSouthAddonDeed()
		{
			Name = "Fireplace South";
		}

		public hex_FirepSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}