// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class KOvenEAddon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new KOvenEAddonDeed();}}
		[ Constructable ]
		public KOvenEAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 281 );
			ac.Hue = 1150;
			ac.Name = "oven";
			AddComponent( ac, -1, 1, 12 );

			ac = new AddonComponent( 269 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, -1, 1, 4 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "oven";
			AddComponent( ac, 0, 0, 7 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1153;
			ac.Name = "Oven settings";
			AddComponent( ac, 0, 1, 7 );

			ac = new AddonComponent( 281 );
			ac.Hue = 1150;
			ac.Name = "oven";
			AddComponent( ac, -1, 0, 12 );

			ac = new AddonComponent( 3859 );
			ac.Hue = 1;
			ac.Name = "dial";
			AddComponent( ac, 0, 0, 17 );

			ac = new AddonComponent( 3859 );
			ac.Hue = 1;
			ac.Name = "dial";
			AddComponent( ac, 0, 1, 17 );

			ac = new AddonComponent( 7027 );
			ac.Hue = 957;
			ac.Name = "burner";
			AddComponent( ac, 0, 1, 12 );

			ac = new AddonComponent( 7027 );
			ac.Hue = 957;
			ac.Name = "burner";
			AddComponent( ac, 0, 0, 12 );

			ac = new AddonComponent( 9232 );
			ac.Hue = 1;
			ac.Name = "door";
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 9232 );
			ac.Hue = 1;
			ac.Name = "door";
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, 0, 0, 4 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, 0, 1, 4 );

			ac = new AddonComponent( 2468 );
			ac.Hue = 1;
			ac.Name = "oven settings";
			AddComponent( ac, 0, 1, 15 );

			ac = new AddonComponent( 2468 );
			ac.Hue = 1;
			ac.Name = "oven settings";
			AddComponent( ac, 0, 0, 15 );


		}
		public KOvenEAddon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class KOvenEAddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new KOvenEAddon();}}
		[Constructable]
		public KOvenEAddonDeed(){Name = "KOvenE";}
		public KOvenEAddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}