// Automatically generated by the
// AddonGenerator script by Arya
// Generator edited 10.Mar.07 by Papler
using System;
using Server;
using Server.Items;
namespace Server.Items
{
	public class KSinkEAddon : BaseAddon {
		public override BaseAddonDeed Deed{get{return new KSinkEAddonDeed();}}
		[ Constructable ]
		public KSinkEAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 4100 );
			ac.Name = "faucet";
			AddComponent( ac, 0, 1, 16 );

			ac = new AddonComponent( 281 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, -1, 1, 12 );

			ac = new AddonComponent( 281 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, -1, 0, 12 );

			ac = new AddonComponent( 269 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, -1, 1, 4 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, 0, 0, 7 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, 0, 1, 7 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, 0, 0, 4 );

			ac = new AddonComponent( 1801 );
			ac.Hue = 1150;
			ac.Name = "Sink";
			AddComponent( ac, 0, 1, 4 );

			ac = new AddonComponent( 2534 );
			AddComponent( ac, 0, 0, 13 );

			ac = new AddonComponent( 2585 );
			AddComponent( ac, 0, 0, 11 );

			ac = new AddonComponent( 3625 );
			ac.Name = "Dawn";
			AddComponent( ac, 0, 1, 17 );

			ac = new AddonComponent( 3607 );
			ac.Hue = 55;
			ac.Name = "sponge";
			AddComponent( ac, 0, 1, 17 );

			ac = new AddonComponent( 9232 );
			ac.Hue = 1150;
			ac.Name = "door";
			AddComponent( ac, 1, 0, 0 );

			ac = new AddonComponent( 9232 );
			ac.Hue = 1150;
			ac.Name = "door";
			AddComponent( ac, 1, 1, 0 );

			ac = new AddonComponent( 4323 );
			ac.Hue = 1153;
			ac.Name = "Sink";
			AddComponent( ac, 0, 1, 10 );


		}
		public KSinkEAddon( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){base.Serialize( writer );writer.Write( 0 );}
		public override void Deserialize( GenericReader reader ){base.Deserialize( reader );reader.ReadInt();}
	}

	public class KSinkEAddonDeed : BaseAddonDeed {
		public override BaseAddon Addon{get{return new KSinkEAddon();}}
		[Constructable]
		public KSinkEAddonDeed(){Name = "KSinkE";}
		public KSinkEAddonDeed( Serial serial ) : base( serial ){}
		public override void Serialize( GenericWriter writer ){	base.Serialize( writer );writer.Write( 0 );}
		public override void	Deserialize( GenericReader reader )	{base.Deserialize( reader );reader.ReadInt();}
	}
}