/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BoulderRock05Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BoulderRock05AddonDeed();
			}
		}

		[ Constructable ]
		public BoulderRock05Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 4954 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 4955 );
			AddComponent( ac, 0, 0, 0 );

		}

		public BoulderRock05Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BoulderRock05AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BoulderRock05Addon();
			}
		}

		[Constructable]
		public BoulderRock05AddonDeed()
		{
			Name = "BoulderRock05";
		}

		public BoulderRock05AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}