/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CherryBlossomTree1eAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CherryBlossomTree1eAddonDeed();
			}
		}

		[ Constructable ]
		public CherryBlossomTree1eAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 9334 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 9333 );
			AddComponent( ac, 0, 0, 0 );

		}

		public CherryBlossomTree1eAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CherryBlossomTree1eAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CherryBlossomTree1eAddon();
			}
		}

		[Constructable]
		public CherryBlossomTree1eAddonDeed()
		{
			Name = "CherryBlossomTree1e";
		}

		public CherryBlossomTree1eAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}