/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CherryBlossomTree1dAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CherryBlossomTree1dAddonDeed();
			}
		}

		[ Constructable ]
		public CherryBlossomTree1dAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 9334 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 9332 );
			AddComponent( ac, 0, 0, 0 );

		}

		public CherryBlossomTree1dAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CherryBlossomTree1dAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CherryBlossomTree1dAddon();
			}
		}

		[Constructable]
		public CherryBlossomTree1dAddonDeed()
		{
			Name = "CherryBlossomTree1d";
		}

		public CherryBlossomTree1dAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}