/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LilacBushTreeAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LilacBushTreeAddonDeed();
			}
		}

		[ Constructable ]
		public LilacBushTreeAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3230 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3146 );
			AddComponent( ac, 0, 1, 21 );
			ac = new AddonComponent( 3146 );
			AddComponent( ac, 1, 0, 20 );
			ac = new AddonComponent( 3146 );
			AddComponent( ac, 1, 1, 20 );
			ac = new AddonComponent( 3146 );
			AddComponent( ac, 1, 1, 31 );
			ac = new AddonComponent( 3145 );
			AddComponent( ac, -1, 1, 10 );
			ac = new AddonComponent( 3142 );
			AddComponent( ac, 1, 0, 15 );

		}

		public LilacBushTreeAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LilacBushTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LilacBushTreeAddon();
			}
		}

		[Constructable]
		public LilacBushTreeAddonDeed()
		{
			Name = "LilacBushTree";
		}

		public LilacBushTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}