/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MLTree12Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MLTree12AddonDeed();
			}
		}

		[ Constructable ]
		public MLTree12Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 15079 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 15078 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 15077 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 15076 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 15075 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 15074 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 15073 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 15072 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 15071 );
			AddComponent( ac, 2, 3, 0 );

		}

		public MLTree12Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MLTree12AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MLTree12Addon();
			}
		}

		[Constructable]
		public MLTree12AddonDeed()
		{
			Name = "MLTree12";
		}

		public MLTree12AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}