/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MLTree22Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MLTree22AddonDeed();
			}
		}

		[ Constructable ]
		public MLTree22Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 14868 );
			AddComponent( ac, -6, 5, 0 );
			ac = new AddonComponent( 14877 );
			AddComponent( ac, 6, -5, 0 );
			ac = new AddonComponent( 14876 );
			AddComponent( ac, 6, -4, 0 );
			ac = new AddonComponent( 14875 );
			AddComponent( ac, 6, -3, 0 );
			ac = new AddonComponent( 14874 );
			AddComponent( ac, 6, -2, 0 );
			ac = new AddonComponent( 14873 );
			AddComponent( ac, 6, -1, 0 );
			ac = new AddonComponent( 14872 );
			AddComponent( ac, 6, 0, 0 );
			ac = new AddonComponent( 14871 );
			AddComponent( ac, 6, 1, 0 );
			ac = new AddonComponent( 14870 );
			AddComponent( ac, 6, 2, 0 );
			ac = new AddonComponent( 14869 );
			AddComponent( ac, 6, 3, 0 );
			ac = new AddonComponent( 14857 );
			AddComponent( ac, 6, 4, 0 );
			ac = new AddonComponent( 14859 );
			AddComponent( ac, 4, 5, 0 );
			ac = new AddonComponent( 14858 );
			AddComponent( ac, 5, 4, 0 );
			ac = new AddonComponent( 14867 );
			AddComponent( ac, -4, 5, 0 );
			ac = new AddonComponent( 14866 );
			AddComponent( ac, -3, 5, 0 );
			ac = new AddonComponent( 14865 );
			AddComponent( ac, -2, 5, 0 );
			ac = new AddonComponent( 14864 );
			AddComponent( ac, -1, 5, 0 );
			ac = new AddonComponent( 14863 );
			AddComponent( ac, 0, 5, 0 );
			ac = new AddonComponent( 14862 );
			AddComponent( ac, 1, 5, 0 );
			ac = new AddonComponent( 14861 );
			AddComponent( ac, 2, 5, 0 );
			ac = new AddonComponent( 14860 );
			AddComponent( ac, 3, 5, 0 );

		}

		public MLTree22Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MLTree22AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MLTree22Addon();
			}
		}

		[Constructable]
		public MLTree22AddonDeed()
		{
			Name = "MLTree22";
		}

		public MLTree22AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}