/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MLTree11Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MLTree11AddonDeed();
			}
		}

		[ Constructable ]
		public MLTree11Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 14854 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 14853 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 14852 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 14851 );
			AddComponent( ac, -1, 2, 0 );

		}

		public MLTree11Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MLTree11AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MLTree11Addon();
			}
		}

		[Constructable]
		public MLTree11AddonDeed()
		{
			Name = "MLTree11";
		}

		public MLTree11AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}