/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MorningGlowTreeAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MorningGlowTreeAddonDeed();
			}
		}

		[ Constructable ]
		public MorningGlowTreeAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3302 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, -1, 1, 20 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, 1, -1, 20 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, 1, 1, 34 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, -1, 1, 16 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, 1, -1, 15 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, 1, 1, 25 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, -1, 1, 10 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, 1, 1, 20 );
			ac = new AddonComponent( 3144 );
			AddComponent( ac, 1, -1, 10 );

		}

		public MorningGlowTreeAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MorningGlowTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MorningGlowTreeAddon();
			}
		}

		[Constructable]
		public MorningGlowTreeAddonDeed()
		{
			Name = "MorningGlowTree";
		}

		public MorningGlowTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}