/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NewTree03Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new NewTree03AddonDeed();
			}
		}

		[ Constructable ]
		public NewTree03Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 12494 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 12510 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 12495 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 12496 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 12497 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 12498 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 12509 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 12508 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 12507 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 12506 );
			AddComponent( ac, 1, 1, 0 );

		}

		public NewTree03Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class NewTree03AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new NewTree03Addon();
			}
		}

		[Constructable]
		public NewTree03AddonDeed()
		{
			Name = "NewTree03";
		}

		public NewTree03AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}