/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class NewTree03NoLeavesAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new NewTree03NoLeavesAddonDeed();
			}
		}

		[ Constructable ]
		public NewTree03NoLeavesAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 12508 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 12506 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 12507 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 12509 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 12510 );
			AddComponent( ac, 1, -1, 0 );

		}

		public NewTree03NoLeavesAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class NewTree03NoLeavesAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new NewTree03NoLeavesAddon();
			}
		}

		[Constructable]
		public NewTree03NoLeavesAddonDeed()
		{
			Name = "NewTree03NoLeaves";
		}

		public NewTree03NoLeavesAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}