/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RedMapleTree2aAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RedMapleTree2aAddonDeed();
			}
		}

		[ Constructable ]
		public RedMapleTree2aAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3475 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 9341 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 9336 );
			AddComponent( ac, 2, 2, 0 );

		}

		public RedMapleTree2aAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RedMapleTree2aAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RedMapleTree2aAddon();
			}
		}

		[Constructable]
		public RedMapleTree2aAddonDeed()
		{
			Name = "RedMapleTree2a";
		}

		public RedMapleTree2aAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}