/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RedMoonGateSquareAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RedMoonGateSquareAddonDeed();
			}
		}

		[ Constructable ]
		public RedMoonGateSquareAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 6095 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 6096 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 6096 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6096 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6097 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6097 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6097 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6100 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6102 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6102 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6102 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6099 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 3546 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6098 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6101 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 6101 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6101 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6103 );
			AddComponent( ac, 2, 2, 0 );

		}

		public RedMoonGateSquareAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RedMoonGateSquareAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RedMoonGateSquareAddon();
			}
		}

		[Constructable]
		public RedMoonGateSquareAddonDeed()
		{
			Name = "RedMoonGateSquare";
		}

		public RedMoonGateSquareAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}