/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RedMoonGateCelticAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RedMoonGateCelticAddonDeed();
			}
		}

		[ Constructable ]
		public RedMoonGateCelticAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 6149 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 6150 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 6150 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 6150 );
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 6151 );
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 6151 );
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 6151 );
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 6154 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 6156 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 6156 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 6156 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 6153 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 3546 );
			ac.Light = LightType.ArchedWindowEast;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 6152 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 6155 );
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 6155 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 6155 );
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 6157 );
			AddComponent( ac, 2, 2, 0 );

		}

		public RedMoonGateCelticAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RedMoonGateCelticAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RedMoonGateCelticAddon();
			}
		}

		[Constructable]
		public RedMoonGateCelticAddonDeed()
		{
			Name = "RedMoonGateCeltic";
		}

		public RedMoonGateCelticAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}