/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class RoseBush02Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new RoseBush02AddonDeed();
			}
		}

		[ Constructable ]
		public RoseBush02Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3217 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3263 );
			AddComponent( ac, 0, 0, 6 );

		}

		public RoseBush02Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class RoseBush02AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new RoseBush02Addon();
			}
		}

		[Constructable]
		public RoseBush02AddonDeed()
		{
			Name = "RoseBush02";
		}

		public RoseBush02AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}