/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TallTree02Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TallTree02AddonDeed();
			}
		}

		[ Constructable ]
		public TallTree02Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3405 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 3406 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3407 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 3408 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3409 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 3410 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 3411 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 3395 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3396 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 3394 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 3393 );
			AddComponent( ac, -2, 2, 0 );

		}

		public TallTree02Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TallTree02AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TallTree02Addon();
			}
		}

		[Constructable]
		public TallTree02AddonDeed()
		{
			Name = "TallTree02";
		}

		public TallTree02AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}