/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TallTree05Addon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TallTree05AddonDeed();
			}
		}

		[ Constructable ]
		public TallTree05Addon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 3439 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 3440 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3446 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 3445 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 3444 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3443 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 3438 );
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 3449 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 3448 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 3447 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 3442 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 3441 );
			AddComponent( ac, 1, -1, 0 );

		}

		public TallTree05Addon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TallTree05AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TallTree05Addon();
			}
		}

		[Constructable]
		public TallTree05AddonDeed()
		{
			Name = "TallTree05";
		}

		public TallTree05AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}