/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TallPineTree : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TallPineTreeDeed();
			}
		}

		[ Constructable ]
		public TallPineTree()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 12453 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 12448 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 12447 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 12457 );
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 12456 );
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 12455 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 12454 );
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 12462 );
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 12461 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 12460 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 12459 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 12458 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 12452 );
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 12451 );
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 12450 );
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 12449 );
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 12446 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 12445 );
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 12444 );
			AddComponent( ac, 2, 3, 0 );

		}

		public TallPineTree( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TallPineTreeDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TallPineTree();
			}
		}

		[Constructable]
		public TallPineTreeDeed()
		{
			Name = "TallPineTree";
		}

		public TallPineTreeDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
