namespace Server.Items
{
    public enum SlayerName
    {
        None,
        Silver,
        OrcSlaying,
        TrollSlaughter,
        OgreTrashing,
        Repond,
        DragonSlaying,
        Terathan,
        SnakesBane,
        LizardmanSlaughter,
        ReptilianDeath,
        DaemonDismissal,
        GargoylesFoe,
        BalronDamnation,
        Exorcism,
        Ophidian,
        SpidersDeath,
        ScorpionsBane,
        ArachnidDoom,
        FlameDousing,
        WaterDissipation,
        Vacuum,
        ElementalHealth,
        EarthShatter,
        BloodDrinking,
        SummerWind,
        ElementalBan,
        Fey,
        Dinosaur,
        Myrmidex,
        Eodon,
        EodonTribe
    }
}